#config custom propt in yml -> https://www.youtube.com/watch?v=RUYV4P68hiE

# https://www.baeldung.com/spring-email
# mailtrap : https://mailtrap.io/signin

# build custom cron -> https://crontab.guru/

properties:
  scheduled:
    # Sauvegarde auto tous les 10 secondes
    autobackup-cron: "0/10 * * * * *"
    # Sauvegarde auto tout les semaines à minuit
    #autobackup-cron: "59 59 23 * * SUN"

    # Envoi de mail tous les 10 secondes
    #auto-send-welcome-email-cron: "0/10 * * * * *"
    # Envoi de mail tout les semaines à minuit
    auto-send-welcome-email-cron: "59 59 23 * * SUN"

server:
  port: 8083

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 066de92fa1bdc0
    password: e03bc6ef02d807
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8

    smtp-auth: true
    smtp-port: 2525
    smtp-host: smtp.mailtrap.io
    smtp-starttls-enable: true
    smtp-starttls-required: true
    ssl-enable: false






